<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>India Employment Monitor</title>
  <style>
    :root{--navy:#10263e;--ink:#17324c;--muted:#6d8093;--line:#dce5ec;--canvas:#f4f7f9;--card:#fff;--teal:#087e8b;--blue:#2867c7;--orange:#e28b3d;--pale:#e6f4f3;--red:#c64f50}
    *{box-sizing:border-box} body{margin:0;background:var(--canvas);color:var(--ink);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
    .app{min-height:100vh;display:grid;grid-template-columns:248px 1fr}.sidebar{padding:26px 17px;background:var(--navy);color:#d2dce6}.logo{display:flex;align-items:center;gap:10px;padding:0 10px 33px;color:#fff;font-size:18px;font-weight:750;letter-spacing:-.4px}.logo i{display:grid;place-items:center;width:29px;height:29px;border-radius:8px;background:#15a6a6;color:#fff;font-style:normal;font-size:15px}.eyebrow{margin:20px 10px 8px;color:#86a1b9;font-size:10px;font-weight:800;letter-spacing:.13em}.nav a{display:flex;align-items:center;gap:12px;padding:11px 12px;margin:3px 0;border-radius:8px;color:#bdccda;text-decoration:none;font-weight:600}.nav a.active,.nav a:hover{background:#1c3a56;color:#fff}.nav b{width:18px;text-align:center;font-size:15px}.source{position:absolute;bottom:24px;margin:0 10px;padding:13px;border-top:1px solid #2c4962;color:#93a9bb;font-size:11px}.source strong{display:block;color:#d6e3ed;margin-bottom:3px}
    main{padding:28px 38px 48px;max-width:1500px;width:100%;margin:auto}.top{display:flex;align-items:center;justify-content:space-between;margin-bottom:29px}.top small{color:var(--muted);font-weight:650}.top h1{margin:4px 0 0;font-size:27px;letter-spacing:-.9px}.controls{display:flex;gap:10px;align-items:center}.select,.export{padding:9px 11px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);font:inherit;font-weight:650}.export{cursor:pointer;background:var(--navy);border-color:var(--navy);color:#fff}.export:hover{background:#1a3b5c}
    .kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:22px}.kpi{padding:18px;background:var(--card);border:1px solid var(--line);border-radius:12px}.kpi-label{display:flex;justify-content:space-between;color:var(--muted);font-size:12px;font-weight:700}.dot{width:8px;height:8px;border-radius:50%;background:var(--teal)}.kpi:nth-child(2) .dot{background:var(--blue)}.kpi:nth-child(3) .dot{background:var(--orange)}.kpi:nth-child(4) .dot{background:var(--red)}.kpi-value{margin:9px 0 3px;font-size:27px;font-weight:760;letter-spacing:-1px}.kpi-foot{color:var(--muted);font-size:11px}.up{color:#0a8663;font-weight:750}.down{color:#a54e44;font-weight:750}
    .grid{display:grid;grid-template-columns:1.45fr .9fr;gap:20px;margin-bottom:20px}.panel{padding:20px;background:var(--card);border:1px solid var(--line);border-radius:12px}.panel-title{display:flex;justify-content:space-between;align-items:baseline;margin-bottom:17px}.panel h2{margin:0;font-size:15px;letter-spacing:-.2px}.panel .sub{color:var(--muted);font-size:11px}.legend{display:flex;gap:15px;color:var(--muted);font-size:11px}.legend span:before{content:"";display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--teal);margin-right:5px}.legend span:last-child:before{background:var(--blue)}
    .chart-wrap{height:255px;position:relative}.chart-wrap svg{width:100%;height:100%;overflow:visible}.axis{stroke:#dce5ec;stroke-width:1}.axis-text{fill:#758698;font-size:11px}.line-a{fill:none;stroke:var(--teal);stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.line-b{fill:none;stroke:var(--blue);stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.point-a{fill:var(--teal);stroke:#fff;stroke-width:2}.point-b{fill:var(--blue);stroke:#fff;stroke-width:2}.value-tag{fill:var(--ink);font-size:11px;font-weight:700}
    .bar-list{margin-top:2px}.bar-row{display:grid;grid-template-columns:115px 1fr 42px;align-items:center;gap:11px;margin:16px 0}.bar-row span{font-size:12px;font-weight:650}.track{height:9px;background:#edf1f4;border-radius:99px;overflow:hidden}.fill{height:100%;border-radius:inherit;background:var(--teal)}.bar-row:nth-child(2) .fill{background:#2d8f9c}.bar-row:nth-child(3) .fill{background:#6aaeb5}.bar-row:nth-child(4) .fill{background:var(--orange)}.bar-row:nth-child(5) .fill{background:#879bab}.bar-row b{text-align:right;font-size:12px}.note{margin:19px 0 0;padding:11px 12px;background:var(--pale);border-radius:7px;color:#366267;font-size:11px}
    .bottom{display:grid;grid-template-columns:.92fr 1.08fr;gap:20px}.gender{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:15px}.gender-box{padding:14px;background:#f6f9fa;border-radius:9px}.gender-box span{display:block;color:var(--muted);font-size:11px;font-weight:700}.gender-box strong{display:block;margin-top:4px;font-size:25px;letter-spacing:-1px}.gender-box small{color:var(--muted);font-size:11px}.table{width:100%;border-collapse:collapse;font-size:12px}.table th{text-align:left;color:var(--muted);font-size:10px;letter-spacing:.04em;text-transform:uppercase}.table th:last-child,.table td:last-child{text-align:right}.table th,.table td{padding:10px 4px;border-bottom:1px solid var(--line)}.table tbody tr:last-child td{border-bottom:0}.badge{display:inline-block;padding:3px 7px;border-radius:99px;background:#edf4fb;color:#386095;font-size:10px;font-weight:750}
    .footer{margin-top:19px;color:var(--muted);font-size:11px}.footer a{color:var(--blue)}
    @media(max-width:1020px){.app{grid-template-columns:1fr}.sidebar{display:none}.kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:680px){main{padding:22px 16px}.top{align-items:flex-start;gap:15px}.controls{flex-direction:column;align-items:stretch}.grid,.bottom{grid-template-columns:1fr}.kpis{grid-template-columns:1fr}.panel{padding:16px}.chart-wrap{height:220px}.bar-row{grid-template-columns:94px 1fr 36px}}
  </style>
</head>
<body>
  <div class="app">
    <aside class="sidebar">
      <div class="logo"><i>↗</i> India workwatch</div>
      <nav class="nav"><p class="eyebrow">DASHBOARD</p><a class="active" href="#overview"><b>▦</b>National overview</a><a href="#trend"><b>⌁</b>Employment trends</a><a href="#sectors"><b>◫</b>Sector mix</a><p class="eyebrow">ANALYSIS</p><a href="#inclusion"><b>◉</b>Inclusion</a><a href="#states"><b>⌖</b>State tracker</a></nav>
      <div class="source"><strong>Data vintage</strong>PLFS calendar year 2024<br>Last updated: April 2025</div>
    </aside>
    <main id="overview">
      <header class="top"><div><small>LABOUR MARKET INTELLIGENCE · INDIA</small><h1>People & employment dashboard</h1></div><div class="controls"><select class="select" aria-label="Reporting period"><option>Calendar year 2024</option><option>Annual report 2023–24</option></select><button class="export" onclick="downloadData()">Export snapshot</button></div></header>
      <section class="kpis" aria-label="Key employment indicators"><div class="kpi"><div class="kpi-label">Labour force participation <i class="dot"></i></div><div class="kpi-value">59.6%</div><div class="kpi-foot"><span class="down">−0.2 pp</span> from calendar 2023</div></div><div class="kpi"><div class="kpi-label">Employment rate (WPR) <i class="dot"></i></div><div class="kpi-value">57.7%</div><div class="kpi-foot"><span class="down">−0.3 pp</span> from calendar 2023</div></div><div class="kpi"><div class="kpi-label">Unemployment rate <i class="dot"></i></div><div class="kpi-value">3.2%</div><div class="kpi-foot"><span class="up">+0.1 pp</span> from calendar 2023</div></div><div class="kpi"><div class="kpi-label">Female participation <i class="dot"></i></div><div class="kpi-value">40.3%</div><div class="kpi-foot"><span class="down">−1.0 pp</span> from calendar 2023</div></div></section>
      <section class="grid" id="trend"><article class="panel"><div class="panel-title"><div><h2>Participation and employment trend</h2><span class="sub">All India · persons aged 15+ · usual status</span></div><div class="legend"><span>LFPR</span><span>WPR</span></div></div><div class="chart-wrap"><svg viewBox="0 0 650 260" role="img" aria-label="Line chart showing labour force participation and worker population ratio rising from 2020-21 to 2023-24"><line class="axis" x1="48" y1="27" x2="625" y2="27"/><line class="axis" x1="48" y1="85" x2="625" y2="85"/><line class="axis" x1="48" y1="143" x2="625" y2="143"/><line class="axis" x1="48" y1="201" x2="625" y2="201"/><text class="axis-text" x="5" y="31">65%</text><text class="axis-text" x="5" y="89">60%</text><text class="axis-text" x="5" y="147">55%</text><text class="axis-text" x="5" y="205">50%</text><path class="line-a" d="M72 145 L245 141 L418 110 L590 84"/><path class="line-b" d="M72 158 L245 154 L418 132 L590 106"/><g><circle class="point-a" cx="72" cy="145" r="5"/><circle class="point-a" cx="245" cy="141" r="5"/><circle class="point-a" cx="418" cy="110" r="5"/><circle class="point-a" cx="590" cy="84" r="5"/><circle class="point-b" cx="72" cy="158" r="5"/><circle class="point-b" cx="245" cy="154" r="5"/><circle class="point-b" cx="418" cy="132" r="5"/><circle class="point-b" cx="590" cy="106" r="5"/><text class="value-tag" x="599" y="80">60.1%</text><text class="value-tag" x="599" y="103">58.2%</text></g><text class="axis-text" x="48" y="231">2020–21</text><text class="axis-text" x="220" y="231">2021–22</text><text class="axis-text" x="393" y="231">2022–23</text><text class="axis-text" x="565" y="231">2023–24</text></svg></div></article>
        <article class="panel" id="sectors"><div class="panel-title"><div><h2>Employment by broad sector</h2><span class="sub">Share of workers · CWS snapshot</span></div></div><div class="bar-list"><div class="bar-row"><span>Agriculture</span><div class="track"><div class="fill" style="width:46%"></div></div><b>46%</b></div><div class="bar-row"><span>Services</span><div class="track"><div class="fill" style="width:32%"></div></div><b>32%</b></div><div class="bar-row"><span>Manufacturing</span><div class="track"><div class="fill" style="width:12%"></div></div><b>12%</b></div><div class="bar-row"><span>Construction</span><div class="track"><div class="fill" style="width:12%"></div></div><b>12%</b></div><div class="bar-row"><span>Other industry</span><div class="track"><div class="fill" style="width:8%"></div></div><b>8%</b></div></div><p class="note">Sector chart is a configurable presentation block—replace with the latest PLFS industry distribution for reporting use.</p></article></section>
      <section class="bottom"><article class="panel" id="inclusion"><div class="panel-title"><div><h2>Participation by gender</h2><span class="sub">All India · age 15+ · calendar year 2024</span></div></div><div class="gender"><div class="gender-box"><span>Male LFPR</span><strong>79.2%</strong><small>WPR: 76.6%</small></div><div class="gender-box"><span>Female LFPR</span><strong>40.3%</strong><small>WPR: 39.0%</small></div></div><p class="note">The gender participation gap is 38.9 percentage points.</p></article><article class="panel" id="states"><div class="panel-title"><div><h2>Reporting notes</h2><span class="sub">Metric definitions</span></div></div><table class="table"><thead><tr><th>Indicator</th><th>Meaning</th><th>Unit</th></tr></thead><tbody><tr><td>LFPR</td><td>People working or seeking work</td><td><span class="badge">Percent</span></td></tr><tr><td>WPR</td><td>People employed</td><td><span class="badge">Percent</span></td></tr><tr><td>UR</td><td>Unemployed share of labour force</td><td><span class="badge">Percent</span></td></tr></tbody></table></article></section>
      <p class="footer">Source: Ministry of Statistics and Programme Implementation, <a href="https://mospi.gov.in/sites/default/files/publication_reports/Key_employment_unemployment_indicators_PLFS_2024_final.pdf" target="_blank" rel="noreferrer">PLFS Key Employment–Unemployment Indicators 2024</a>. National headline metrics use usual status (ps+ss), persons aged 15+.</p>
    </main>
  </div>
  <script>
    function downloadData(){const data='Indicator,Value,Period\nLabour force participation rate,59.6%,Calendar 2024\nWorker population ratio,57.7%,Calendar 2024\nUnemployment rate,3.2%,Calendar 2024\nFemale LFPR,40.3%,Calendar 2024';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download='india-employment-snapshot.csv';a.click();URL.revokeObjectURL(a.href)}
  </script>
</body>
</html>
